/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminBlueprintsRouteImport } from './routes/admin/blueprints'
import { Route as AdminCompetencyUnitsRouteImport } from './routes/admin/competency-units'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminExamsRouteImport } from './routes/admin/exams'
import { Route as AdminMasterGanisphRouteImport } from './routes/admin/master-ganisph'
import { Route as AdminQualificationsRouteImport } from './routes/admin/qualifications'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ExamAttemptIdRouteImport } from './routes/exam/$attemptId'
import { Route as ParticipantIndexRouteImport } from './routes/participant/index'
import { Route as ParticipantExamsRouteImport } from './routes/participant/exams'
import { Route as ParticipantProfileRouteImport } from './routes/participant/profile'
import { Route as ParticipantResultsRouteImport } from './routes/participant/results'
import { Route as ResultsAttemptIdRouteImport } from './routes/results/$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlueprintsRoute = AdminBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetencyUnitsRoute = AdminCompetencyUnitsRouteImport.update({
  id: '/competency-units',
  path: '/competency-units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterGanisphRoute = AdminMasterGanisphRouteImport.update({
  id: '/master-ganisph',
  path: '/master-ganisph',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQualificationsRoute = AdminQualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ExamAttemptIdRoute = ExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantExamsRoute = ParticipantExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantProfileRoute = ParticipantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantResultsRoute = ParticipantResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ParticipantRoute,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/competency-units': typeof AdminCompetencyUnitsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/master-ganisph': typeof AdminMasterGanisphRoute
  '/admin/qualifications': typeof AdminQualificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/participant/exams': typeof ParticipantExamsRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/results': typeof ParticipantResultsRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/participant/': typeof ParticipantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/competency-units': typeof AdminCompetencyUnitsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/master-ganisph': typeof AdminMasterGanisphRoute
  '/admin/qualifications': typeof AdminQualificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/participant/exams': typeof ParticipantExamsRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/results': typeof ParticipantResultsRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/admin': typeof AdminIndexRoute
  '/participant': typeof ParticipantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/competency-units': typeof AdminCompetencyUnitsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/master-ganisph': typeof AdminMasterGanisphRoute
  '/admin/qualifications': typeof AdminQualificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/participant/exams': typeof ParticipantExamsRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/results': typeof ParticipantResultsRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/participant/': typeof ParticipantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/participant'
    | '/admin/audit-logs'
    | '/admin/blueprints'
    | '/admin/competency-units'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/master-ganisph'
    | '/admin/qualifications'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/subjects'
    | '/admin/users'
    | '/exam/$attemptId'
    | '/participant/exams'
    | '/participant/profile'
    | '/participant/results'
    | '/results/$attemptId'
    | '/admin/'
    | '/participant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/blueprints'
    | '/admin/competency-units'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/master-ganisph'
    | '/admin/qualifications'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/subjects'
    | '/admin/users'
    | '/exam/$attemptId'
    | '/participant/exams'
    | '/participant/profile'
    | '/participant/results'
    | '/results/$attemptId'
    | '/admin'
    | '/participant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/participant'
    | '/admin/audit-logs'
    | '/admin/blueprints'
    | '/admin/competency-units'
    | '/admin/enrollments'
    | '/admin/exams'
    | '/admin/master-ganisph'
    | '/admin/qualifications'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/subjects'
    | '/admin/users'
    | '/exam/$attemptId'
    | '/participant/exams'
    | '/participant/profile'
    | '/participant/results'
    | '/results/$attemptId'
    | '/admin/'
    | '/participant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParticipantRoute: typeof ParticipantRouteWithChildren
  ExamAttemptIdRoute: typeof ExamAttemptIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blueprints': {
      id: '/admin/blueprints'
      path: '/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AdminBlueprintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competency-units': {
      id: '/admin/competency-units'
      path: '/competency-units'
      fullPath: '/admin/competency-units'
      preLoaderRoute: typeof AdminCompetencyUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master-ganisph': {
      id: '/admin/master-ganisph'
      path: '/master-ganisph'
      fullPath: '/admin/master-ganisph'
      preLoaderRoute: typeof AdminMasterGanisphRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qualifications': {
      id: '/admin/qualifications'
      path: '/qualifications'
      fullPath: '/admin/qualifications'
      preLoaderRoute: typeof AdminQualificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/exam/$attemptId': {
      id: '/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof ExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/exams': {
      id: '/participant/exams'
      path: '/exams'
      fullPath: '/participant/exams'
      preLoaderRoute: typeof ParticipantExamsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/profile': {
      id: '/participant/profile'
      path: '/profile'
      fullPath: '/participant/profile'
      preLoaderRoute: typeof ParticipantProfileRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/results': {
      id: '/participant/results'
      path: '/results'
      fullPath: '/participant/results'
      preLoaderRoute: typeof ParticipantResultsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBlueprintsRoute: typeof AdminBlueprintsRoute
  AdminCompetencyUnitsRoute: typeof AdminCompetencyUnitsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminMasterGanisphRoute: typeof AdminMasterGanisphRoute
  AdminQualificationsRoute: typeof AdminQualificationsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBlueprintsRoute: AdminBlueprintsRoute,
  AdminCompetencyUnitsRoute: AdminCompetencyUnitsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminMasterGanisphRoute: AdminMasterGanisphRoute,
  AdminQualificationsRoute: AdminQualificationsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParticipantRouteChildren {
  ParticipantExamsRoute: typeof ParticipantExamsRoute
  ParticipantProfileRoute: typeof ParticipantProfileRoute
  ParticipantResultsRoute: typeof ParticipantResultsRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
}

const ParticipantRouteChildren: ParticipantRouteChildren = {
  ParticipantExamsRoute: ParticipantExamsRoute,
  ParticipantProfileRoute: ParticipantProfileRoute,
  ParticipantResultsRoute: ParticipantResultsRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
}

const ParticipantRouteWithChildren = ParticipantRoute._addFileChildren(
  ParticipantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ParticipantRoute: ParticipantRouteWithChildren,
  ExamAttemptIdRoute: ExamAttemptIdRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
